// Worked examples + maturity map — the single source that feeds (a) tool descriptions on the MCP
// wire, (b) cork_capabilities search/topic "filled invocation templates", and (c) teaching error
// payloads (the corrected example an agent can retry with). Shipping examples in tool definitions
// measurably raises parameter accuracy (Anthropic "Advanced tool use": 72%→90%) [C13].
//
// The demo pool is the canonical vnet fixture (deployed on the Tenderly virtual mainnet via
// impersonation — recipe: scripts/DeployDemoPool.s.sol / notes/experiments/03-vnet-fixture.md).
// It exists ONLY on the vnet: run these against `CORK_RPC_URL=<vnet>`; on real mainnet substitute
// a live poolId from api-phoenix.cork.tech/v1/pools/.
import type { ToolName } from "./registry.ts";

export const DEMO_POOL_ID = "0xceebea356e5159c9cb06612c39ef2e6e0fe9cd3bb047541e26e0c0767bd1c16a" as const;
export const DEMO_ACCOUNT = "0xc0ffee0000000000000000000000000000000001" as const;
const SUSDE = "0x9D39A5DE30e57443BfF2A8307A4256c8797A3497";
const VBUSDC = "0x53E82ABbb12638F09d9e624578ccB666217a765e";

// A real safeSwap Bundler3 multicall (1 sUSDe out of the demo pool, pre-funded), generated by
// cork_prepare_phoenix — decodes to one labeled cork leg.
const DEMO_MULTICALL =
  "0x374f435d000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000ccccccccccccbad6f772a511b337d9ccc957040700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4d5f2e59eceebea356e5159c9cb06612c39ef2e6e0fe9cd3bb047541e26e0c0767bd1c16a0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000c0ffee00000000000000000000000000000000010000000000000000000000000000000000000000000000001bc16d674ec8000000000000000000000000000000000000000000000000000000000000001e8480000000000000000000000000000000000000000000000000000000006a5e14e600000000000000000000000000000000000000000000000000000000";

// The SAME demo multicall SIGNED as an EIP-1559 tx to the mainnet Bundler3 by a throwaway key
// (Anvil dev account #1, 0x70997970C51812dc3A010C7d01b50e0d17dc79C8) — the decode kind:"tx"
// fixture: recovered signer + named target + the identical labeled legs. Exported so the eval
// task set reuses THIS constant, and BOUND to the source of truth by a parity test
// (packages/core/test/decode-tx.test.ts re-signs the same fields with the same key — ECDSA is
// deterministic per RFC 6979 — and asserts byte equality, so this literal cannot drift).
export const DEMO_SIGNED_TX =
  "0x02f902720107843b9aca008506fc23ac0083061a80946566194141eefa99af43bb5aa71460ca2dc9024580b90204374f435d000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000ccccccccccccbad6f772a511b337d9ccc957040700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4d5f2e59eceebea356e5159c9cb06612c39ef2e6e0fe9cd3bb047541e26e0c0767bd1c16a0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000c0ffee00000000000000000000000000000000010000000000000000000000000000000000000000000000001bc16d674ec8000000000000000000000000000000000000000000000000000000000000001e8480000000000000000000000000000000000000000000000000000000006a5e14e600000000000000000000000000000000000000000000000000000000c080a03f1e02aab6f5035aa44fe1a05c3305a27f14079b3577b3d42e7d5219fc22e8aaa0457efc4d172aa72d297fb0ba25382f5b23091d4297711c4f58d4859b4f0e8f71";

export interface ToolExample {
  title: string;
  input: Record<string, unknown>;
}

/** 2–3 worked examples per tool; the FIRST is the one inlined into the wire description. */
export const TOOL_EXAMPLES: Record<ToolName, readonly ToolExample[]> = {
  cork_query: [
    { title: "Read a pool's full live market state (demo pool, vnet)", input: { resource: "market", filters: { poolId: DEMO_POOL_ID } } },
    { title: "Token balances an account holds in a pool", input: { resource: "account-state", filters: { poolId: DEMO_POOL_ID, account: DEMO_ACCOUNT } } },
    { title: "Deployed Cork contract addresses (no RPC needed)", input: { resource: "protocol-config" } },
    { title: "Open RFQs awaiting quotes (underwriter discovery feed; add filters.rfqId for one record with all answers)", input: { resource: "rfqs", chainId: 42161, filters: { state: "open", withAnswers: true } } },
    { title: "Predict a market before it exists: pool id + cST/cPT + constraint for a pair (Arbitrum; recipe = the approved liquidity recipe CONTRACT)", input: { resource: "market-predict", chainId: 42161, filters: { collateralAsset: "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2", referenceAsset: "0xdDb46999F8891663a8F2828d25298f70416d7610", expiry: "1900000000", recipe: "0xA39d552802b2D3A9be6F5DCDD2C6961DaeD1234D", args: "0x0000000000000000000000000000000000000000000000000de0b6b3a7640000" } } },
    { title: "The approved recipe contracts with their live constants + argument shapes (Arbitrum)", input: { resource: "registry-recipes", chainId: 42161 } },
    { title: "Enumerate a pool's whitelist rows (event-derived; global rows ride along)", input: { resource: "whitelisted-addresses", chainId: 42161, filters: { poolId: DEMO_POOL_ID } } },
  ],
  cork_compute: [
    { title: "How much cST + reference does 1 sUSDe out cost right now?", input: { params: { kind: "cst-swap-rate", poolId: DEMO_POOL_ID, collateralAssetsOut: "1000000000000000000" } } },
    { title: "Rollover premium floor (pure math, no RPC)", input: { params: { kind: "rollover-premium-floor", dstCstProduced: "1000000000000000000000", minPremiumPerShare: "20000000000000000" } } },
    { title: "Worst-case impairment floor over 1 day", input: { params: { kind: "impairment-floor", poolId: DEMO_POOL_ID, horizonSeconds: 86400 } } },
    { title: "Ask a recipe what constraint it imposes on a pair — THE step that produces what a JIT order signs (Arbitrum)", input: { chainId: 42161, params: { kind: "resolve-recipe", recipe: "0xA39d552802b2D3A9be6F5DCDD2C6961DaeD1234D", collateralAsset: "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2", referenceAsset: "0xdDb46999F8891663a8F2828d25298f70416d7610", args: "0x0000000000000000000000000000000000000000000000000de0b6b3a7640000" } } },
    { title: "Current decayed price of a Fusion dutch-auction order (pin the moment with at.timestamp)", input: { at: { timestamp: "1787962200" }, params: { kind: "dutch-auction-price", order: { salt: "72116775394861435818731221900729193628876322478708569", maker: DEMO_ACCOUNT, receiver: "0x0000000000000000000000000000000000000000", makerAsset: SUSDE, takerAsset: VBUSDC, makingAmount: "1000000000000000000", takingAmount: "1000000", makerTraits: "904625697166532776746648320380374280103671755200316906558262375061821325312", extension: "0x0000006e0000006e0000006e0000006e0000006e0000003700000000000000002ad5004c60e16e54d5007c80ce329adde5b51ef5000000000000006a922100000e100f4240020aae6003840493e00384000000000000002ad5004c60e16e54d5007c80ce329adde5b51ef5000000000000006a922100000e100f4240020aae6003840493e0038400000000000000" } } } },
  ],
  cork_decode: [
    { title: "Decode a Bundler3 multicall to labeled Cork legs", input: { kind: "calldata", data: DEMO_MULTICALL } },
    { title: "Validate a SIGNED raw tx BEFORE broadcasting: recovered signer, named target, labeled legs", input: { kind: "tx", data: DEMO_SIGNED_TX } },
    { title: "Decode a LOP v4 order: makerTraits breakdown + recomputed orderHash", input: { kind: "order", data: { salt: "1", maker: DEMO_ACCOUNT, receiver: "0x0000000000000000000000000000000000000000", makerAsset: SUSDE, takerAsset: VBUSDC, makingAmount: "1000000000000000000", takingAmount: "1000000", makerTraits: "0" } } },
    { title: "Decode one event log to named args (settler OrderSettled)", input: { kind: "event", data: { topics: ["0xd4250d6114a611e75d68b1c6f14c61e967863d8ac20bc8ebfa4e5f28f6647366", "0x93cec2a3f4ee806583f173da81e62a11d0a8b392ec9f1509e5f2228006f52d84"], data: "0x" } } },
    { title: "Label every log in a tx receipt", input: { kind: "receipt", data: { status: "0x1", logs: [{ address: SUSDE, topics: ["0xd4250d6114a611e75d68b1c6f14c61e967863d8ac20bc8ebfa4e5f28f6647366", "0x93cec2a3f4ee806583f173da81e62a11d0a8b392ec9f1509e5f2228006f52d84"], data: "0x" }] } } },
  ],
  cork_capabilities: [
    { title: "Find the right tool/variant for 'unwind'", input: { search: "unwind" } },
    { title: "Full doc for one tool", input: { topic: "compute" } },
    { title: "How to sign & broadcast a prepared artifact (doc topic; aliases: execute, broadcast)", input: { topic: "signing" } },
    { title: "Re-derive deployed addresses via CREATE2", input: { topic: "verify" } },
  ],
  cork_prepare_phoenix: [
    { title: "Unsigned deposit bundle (10 sUSDe into the demo pool)", input: { chainId: 1, account: DEMO_ACCOUNT, clientRequestId: "demo-deposit-0001", fundingMode: "erc20-approve", action: { type: "deposit", poolId: DEMO_POOL_ID, collateralAssetsIn: "10000000000000000000", receiver: DEMO_ACCOUNT, minCptAndCstSharesOut: "1" } } },
    { title: "Unsigned swap bundle (1 sUSDe out, capped inputs)", input: { chainId: 1, account: DEMO_ACCOUNT, clientRequestId: "demo-swap-0001", action: { type: "swap", poolId: DEMO_POOL_ID, collateralAssetsOut: "1000000000000000000", receiver: DEMO_ACCOUNT, maxCstSharesIn: "2000000000000000000", maxReferenceAssetsIn: "2000000" } } },
    { title: "Unsigned ERC-20 approve for the erc20-approve funding mode (omit amount = unlimited)", input: { chainId: 1, account: DEMO_ACCOUNT, clientRequestId: "demo-onboard-0001", action: { type: "authority-onboard", token: SUSDE, spender: "0xCCcCcCCCcccCBaD6F772a511B337d9CCc9570407" } } },
    { title: "exerciseForSelf via an integrator-deployed ForSelf adapter (parameter-blind session-key wallets, e.g. a Zyfai Safe)", input: { chainId: 42161, account: DEMO_ACCOUNT, clientRequestId: "demo-forself-ex-0001", forSelf: { adapter: "0xaaaAAAAAAaAaaaaAAAaaAAAAaAaaaaAaaAaaAA01" }, action: { type: "exercise", poolId: DEMO_POOL_ID, cstSharesIn: "1000000000000000000", receiver: DEMO_ACCOUNT, minCollateralAssetsOut: "900000000000000000", maxReferenceAssetsIn: "50000000" } } },
  ],
  cork_prepare_orders: [
    { title: "Signable maker order: sell 1 sUSDe for 1 vbUSDC", input: { chainId: 1, account: DEMO_ACCOUNT, clientRequestId: "demo-order-0001", action: { type: "maker-order", poolId: DEMO_POOL_ID, side: "SELL", makerAsset: SUSDE, takerAsset: VBUSDC, makingAmount: "1000000000000000000", takingAmount: "1000000", expirySeconds: 3600 } } },
    { title: "Buy cover as maker at YOUR price + expiry, with just-in-time market creation (Arbitrum): makingAmount/takingAmount set the premium, expirySeconds bounds the order, jitMarket pins the pool identity at signing", input: { chainId: 42161, account: DEMO_ACCOUNT, clientRequestId: "demo-jit-buy-0001", action: { type: "maker-order", poolId: "0x1111111111111111111111111111111111111111111111111111111111111111", side: "BUY", makerAsset: "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2", takerAsset: "0x53E82ABbb12638F09d9e624578ccB666217a765e", makingAmount: "10000000000000000", takingAmount: "50000000000000000", expirySeconds: 86400, jitMarket: { collateralAsset: "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2", referenceAsset: "0xdDb46999F8891663a8F2828d25298f70416d7610", expiryTimestamp: "1790000000", recipe: "0xA39d552802b2D3A9be6F5DCDD2C6961DaeD1234D" } } } },
    { title: "Cancel calldata for a resting order", input: { chainId: 1, account: DEMO_ACCOUNT, clientRequestId: "demo-cancel-0001", action: { type: "cancel", orderHash: "0x1111111111111111111111111111111111111111111111111111111111111111", makerTraits: "0" } } },
    { title: "Unsigned fill calldata for a resting venue order (Arbitrum)", input: { chainId: 42161, account: DEMO_ACCOUNT, clientRequestId: "demo-fill-0001", action: { type: "taker-fill", orderHash: "0x1111111111111111111111111111111111111111111111111111111111111111" } } },
    { title: "Fill through a ForSelf adapter (fillOrderForSelf — the bought asset is forced to the calling account)", input: { chainId: 42161, account: DEMO_ACCOUNT, clientRequestId: "demo-forself-fill-0001", action: { type: "taker-fill", orderHash: "0x1111111111111111111111111111111111111111111111111111111111111111", forSelf: { adapter: "0xaaaAAAAAAaAaaaaAAAaaAAAAaAaaaaAaaAaaAA01", poolId: DEMO_POOL_ID } } } },
    { title: "Finalize a caller-signed maker order into a cork_submit artifact", input: { chainId: 42161, account: DEMO_ACCOUNT, clientRequestId: "demo-final-0001", action: { type: "finalize-maker-order", prepared: { kind: "maker-order", lop: "0x111111125421ca6dc452d289314280a0f8842a65", typedData: { domain: { chainId: 42161, verifyingContract: "0x111111125421ca6dc452d289314280a0f8842a65" }, message: { salt: "1", maker: DEMO_ACCOUNT, receiver: "0x0000000000000000000000000000000000000000", makerAsset: SUSDE, takerAsset: VBUSDC, makingAmount: "1000000000000000000", takingAmount: "1000000", makerTraits: "0" } }, orderHash: "0x1111111111111111111111111111111111111111111111111111111111111111", extension: "0x", clientRequestId: "demo-final-0001" }, signature: `0x${"11".repeat(32)}${"22".repeat(32)}1b`, listing: { side: "SELL", premium: 4.1, expiry: 0, nonce: "0", allowsPartialFills: true } } } },
    { title: "Signable rollover order (Arbitrum, ExactSettler, all-or-nothing)", input: { chainId: 42161, account: DEMO_ACCOUNT, clientRequestId: "demo-roll-0001", action: { type: "rollover-intent", settler: "0x983270AE48545665Cee4D7EF61C65fF3fdC8222D", rolloverContract: DEMO_ACCOUNT, srcPoolId: "0x1111111111111111111111111111111111111111111111111111111111111111", dstPoolId: "0x2222222222222222222222222222222222222222222222222222222222222222", srcCstToken: SUSDE, dstCstToken: VBUSDC, premiumToken: SUSDE, orderSize: "250000000000000000000", minPremiumPerShare: "12000000000000000", openDeadline: "1795000000", fillDeadline: "1795604800" } } },
  ],
  cork_prepare_market: [
    { title: "Unsigned oracle-deploy tx for a pair (registry.deploy(ca, ref, mode) — permissionless, idempotent; Arbitrum)", input: { chainId: 42161, clientRequestId: "demo-market-0001", action: { type: "deploy-wrapper", collateralAsset: "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2", referenceAsset: "0xdDb46999F8891663a8F2828d25298f70416d7610", mode: "price" } } },
    { title: "Unsigned fixed-rate-oracle deploy tx (keyed on the RATE, no pair; the oracle a FIXED order's rateOverride produces)", input: { chainId: 42161, clientRequestId: "demo-market-0002", action: { type: "deploy-fixed-oracle", rate: "1000000000000000000" } } },
  ],
  cork_track: [
    { title: "Digest-pin an artifact you were handed", input: { mode: "verify", subject: { kind: "artifact", artifact: { any: "json" } } } },
    { title: "Verify a pool against chain (MarketId re-hash)", input: { mode: "verify", subject: { kind: "marketRef", poolId: DEMO_POOL_ID } } },
    { title: "Reconcile a tx receipt", input: { mode: "reconcile", subject: { kind: "txHash", txHash: "0x2222222222222222222222222222222222222222222222222222222222222222" } } },
    { title: "Dry-run a prepared bundle before signing (wouldRevert + reason)", input: { mode: "simulate", subject: { kind: "artifact", artifact: { bundler3: "0x1FA4431bC113D308beE1d46B0e98Cb805FB48C13", multicall: "0x374f435d", account: DEMO_ACCOUNT } }, chainId: 42161 } },
  ],
  cork_submit: [
    // The maker below is the well-known Anvil dev account #0 and the signature is a REAL EIP-712
    // signature by it over this exact OrderData — cork_submit recovers the signer against the
    // recomputed digest [K3], so a made-up signature would (correctly) return a conflict.
    { title: "Relay a signed rollover order to the venue (intent hash + digest recomputed before relay)", input: { chainId: 42161, clientRequestId: "demo-submit-0001", action: { type: "rollover-order", order: { user: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", settler: "0x983270AE48545665Cee4D7EF61C65fF3fdC8222D", fillerHint: "0x0000000000000000000000000000000000000000", exclusiveFiller: "0x0000000000000000000000000000000000000000", srcCstToken: SUSDE, dstCstToken: VBUSDC, premiumToken: SUSDE, rolloverContract: DEMO_ACCOUNT, originChainId: "42161", destinationChainId: "42161", openDeadline: "1795000000", fillDeadline: "1795604800", orderSalt: "8811723641", orderSize: "250000000000000000000", minPremiumPerShare: "12000000000000000", allowPartialFills: false, allowUnderfill: false, premiumPaymentMode: 0, rolloverIntentHash: "0x93cec2a3f4ee806583f173da81e62a11d0a8b392ec9f1509e5f2228006f52d84", rolloverParams: { srcCstToken: SUSDE, dstCstToken: VBUSDC, minCaReceived: "0", minSharesOut: "0", srcPoolId: "0x1111111111111111111111111111111111111111111111111111111111111111", dstPoolId: "0x2222222222222222222222222222222222222222222222222222222222222222", settler: "0x983270AE48545665Cee4D7EF61C65fF3fdC8222D" } }, intent: { rolloverContract: DEMO_ACCOUNT, deadline: "1795604800", nonce: "1", preRolloverHooks: [], midRolloverHooks: [], postRolloverHooks: [], premiumHooks: [] }, signature: "0x97ccd3eb8faa84248754800ef050b1ee4ae6f2f073df6f5cf2b28c9bf6478e052af96f77cd1291a576bcdb77ba3bd1df363f4fc4e55624b353b1d99c34e795ea1b" } } },
    { title: "Open an RFQ (buyer): cover 50k, acceptable parameter envelope", input: { chainId: 42161, clientRequestId: "demo-rfq-0001", action: { type: "rfq-open", requester: DEMO_ACCOUNT, referenceAsset: SUSDE, collateralAsset: { one_of: [VBUSDC] }, modes: ["liquidity_impairment"], packageIds: ["balanced-v1"], expiryWindow: { notBefore: 1795000000, notAfter: 1795604800 }, notionalAssets: "50000000000", validUntil: 1794900000, signature: "0x00" } } },
  ],
};

// ─── Maturity map [R6]: specified (schema only) / implemented (code path, backend-gated) /
//     activated (works now with built-in defaults). Reasons are the same closed warning codes the
//     gated call would return — an agent can see the outcome without spending the call.
export type MaturityStatus = "activated" | "implemented" | "specified";
export interface VariantMaturity {
  status: MaturityStatus;
  reason?: string;
}
export interface ToolMaturity {
  status: MaturityStatus;
  reason?: string;
  variants?: Record<string, VariantMaturity>;
}

export const MATURITY: Record<ToolName, ToolMaturity> = {
  cork_query: {
    status: "activated",
    variants: {
      market: { status: "activated" },
      "account-state": { status: "activated", reason: "balances + funding allowances (corkAdapter + Permit2 spenders)" },
      "pool-whitelist": { status: "activated" },
      "protocol-config": { status: "activated" },
      markets: { status: "activated", reason: "centralized (venue /v1/pools) or full-decentralized (HyperSync MarketCreated scan, needs ENVIO_API_TOKEN)" },
      "whitelisted-addresses": { status: "activated", reason: "event-derived enumeration (WhitelistManager add/remove/enable events over HyperSync, needs ENVIO token) + live-view [K7] verification when an RPC resolves; single-account checks are pool-whitelist" },
      flows: { status: "activated", reason: "centralized (/v1/rollover, filters.kind orders|fills|contracts); kind fills|contracts also full-decentralized via HyperSync" },
      "limit-order-markets": { status: "activated", reason: "venue-backed (centralized mode)" },
      orderbook: { status: "activated", reason: "venue-backed (centralized mode)" },
      fills: { status: "activated", reason: "centralized (venue) or full-decentralized (HyperSync OrderFilled scan)" },
      "registry-assets": { status: "activated", reason: "MarketRegistry 2.1.0 chain views — Arbitrum One (42161): two named source slots (priceSource/navSource) + token self-description; filters.address for a single asset" },
      rfqs: { status: "activated", reason: "venue-backed (centralized mode): GET /v1/rfqs discovery feed + single get via filters.rfqId; venue-only in every mode (RFQ requests/answers never bind and emit no events)" },
      "registry-oracle": { status: "activated", reason: "2.1.0 mode-keyed pair wrappers (price|nav via 3-arg lookupWrapper + simulated deploy: deployed/deployable/why-not) AND fixed-rate oracles keyed on the rate (filters.rate) — 42161" },
      "registry-recipes": { status: "activated", reason: "2.1.0 recipes-as-contracts: address + source + description + live constants + args annotation (isRecipe is the only membership gate) — 42161" },
      "registry-denominations": { status: "activated", reason: "2.1.0 label→unit map with display-label resolution (pseudo-unit table + unit symbol); labelHash is the identity — 42161" },
      "registry-feeds": { status: "activated", reason: "2.1.0 directed conversion-feed edges with live aggregator answers (decimals drift visible) — 42161" },
      "market-predict": { status: "activated", reason: "MarketRegistry 2.1.0 + adapter derivation (42161): recipe contract + off-chain-resolved constraint (recipe.resolve), LOCAL pool id (computeMarketId), cST/cPT via state-override simulation, and pool existence — the same derivation a JIT LOP fill runs; identity PINNED once an order carrying the constraint is signed" },
    },
  },
  cork_compute: {
    status: "activated",
    variants: {
      "cst-swap-rate": { status: "activated" },
      "unwind-rate": { status: "activated" },
      "impairment-floor": { status: "activated" },
      "rollover-premium-floor": { status: "activated" },
      "dutch-auction-price": { status: "activated", reason: "pure local pricing of 1inch Fusion v3.1 dutch-auction orders, reconstructed from the order's own extension bytes [K3]; wei-exact vs the deployed settlement getters on mainnet+Arbitrum (incl. a real production order); at.timestamp pins the moment, baseFeeWei omitted = upper-bound" },
      "rfq-quote": { status: "specified", reason: "phase_gated (pricing MODEL deliberately deferred — a recommended quote is a product decision, not missing infra; the constraint math it would build on is already live as resolve-recipe)" },
      "resolve-recipe": { status: "activated", reason: "2.1.0 recipe.resolve staticcall — THE step that produces the constraint a JIT order signs (42161). The pre-2.1.0 percentage-band math survives behind legacy:true + CORK_ENABLE_DEPRECATED=1" },
    },
  },
  cork_decode: {
    status: "activated",
    variants: {
      calldata: { status: "activated" },
      tx: { status: "activated", reason: "pure local: a SIGNED raw transaction (legacy RLP or typed envelope) → recovered signer + to/value/chainId/nonce/gas, target named against known Cork deployments, inner calldata decoded to the same labeled legs [K3] — the validate-before-broadcast step" },
      order: { status: "activated", reason: "pure local: LOP v4 order (hex tuple or JSON fields) → full makerTraits breakdown + recomputed EIP-712 orderHash; caller-claimed hashes are cross-checked, never trusted [K3]" },
      event: { status: "activated", reason: "pure local: one log {topics,data} → named args against the source-verified Cork/rollover/LOP/ERC-20 ABI set; unverified layouts are labeled raw, never guessed" },
      receipt: { status: "activated", reason: "pure local: labels every log in a receipt against the known ABI set; receipt claims (status, gas) are echoed as claims" },
    },
  },
  cork_capabilities: { status: "activated" },
  cork_prepare_phoenix: {
    status: "activated",
    variants: {
      "13 adapter actions (mint…unwind-exercise-other)": { status: "activated" },
      "authority-onboard": { status: "activated", reason: "unsigned DIRECT ERC-20 approve tx (amount omitted = unlimited) — not a bundle leg, since an allowance is keyed to msg.sender; spender role (corkAdapter/Permit2) disclosed" },
      "authority-revoke": { status: "activated", reason: "unsigned DIRECT ERC-20 approve(spender, 0) tx zeroing the allowance" },
    },
  },
  cork_prepare_orders: {
    status: "activated",
    variants: {
      "maker-order": { status: "activated" },
      "finalize-maker-order": { status: "activated", reason: "reconstruction + salt↔extension binding check, then EOA ecrecover or (for contract makers, e.g. a Safe) the ERC-1271 isValidSignature staticcall the fill itself performs; emits a content-addressed cork_submit artifact; never signs [K1]" },
      cancel: { status: "activated" },
      "taker-fill": { status: "activated", reason: "bounded venue orderbook lookup + local orderHash re-verification, then canonical uint256-tuple fill calldata (unsigned); `forSelf` emits the fill as a call to an integrator-deployed ForSelf adapter instead (parameter-blind session-key wallets)" },
      "rollover-intent": { status: "activated", reason: "offline typed-data build; domain-separator parity proven vs both live Arbitrum settlers" },
    },
  },
  cork_prepare_market: {
    status: "activated",
    reason: "MarketRegistry 2.1.0 verified on-chain 2026-08-03 (Arbitrum One, full redeploy — every address changed): deploy-wrapper builds the permissionless idempotent registry.deploy(ca, ref, mode) tx; deploy-fixed-oracle builds deployFixedRateOracle(rate)",
    variants: { "deploy-wrapper": { status: "activated" }, "deploy-fixed-oracle": { status: "activated" } },
  },
  cork_track: {
    status: "activated",
    variants: {
      "verify/artifact": { status: "activated" },
      "verify/marketRef": { status: "activated" },
      "reconcile/txHash": { status: "activated" },
      "simulate/artifact": { status: "activated", reason: "eth_call dry-run of frozen bytes (wouldRevert + reason + gas estimate); other subject kinds have nothing executable" },
      "reconcile/orderHash": { status: "activated", reason: "venue lifecycle + [K7] chain verification: settler orderStatus() over RPC (automatic) and event history via HyperRPC (needs ENVIO_API_TOKEN)" },
      "reconcile/submissionRef": { status: "activated", reason: "same as reconcile/orderHash; 32-byte digests only" },
    },
  },
  cork_submit: {
    status: "implemented",
    reason: "all four off-chain venue writes wired; activation pending the first live accepted POST",
    variants: {
      "rollover-order": { status: "implemented", reason: "K3 intent-hash + orderDigest recomputed before relay" },
      "lop-order": { status: "implemented", reason: "orderHash recomputed locally; extension/salt commitment pre-flight" },
      "rfq-open": { status: "implemented" },
      "rfq-answer": { status: "implemented" },
    },
  },
};

/** The wire-description example line for a tool (first example, compact JSON). */
export function descriptionExample(name: ToolName): string {
  const ex = TOOL_EXAMPLES[name]?.[0];
  return ex ? ` Example — ${ex.title}: ${JSON.stringify(ex.input)}` : "";
}
