// Worked examples + maturity map — the single source that feeds (a) tool descriptions on the MCP
// wire, (b) cork_capabilities search/topic "filled invocation templates", and (c) teaching error
// payloads (the corrected example an agent can retry with). Shipping examples in tool definitions
// measurably raises parameter accuracy (Anthropic "Advanced tool use": 72%→90%) [C13].
//
// The demo pool is the canonical vnet fixture (deployed on the Tenderly virtual mainnet via
// impersonation — recipe: scripts/DeployDemoPool.s.sol / notes/experiments/03-vnet-fixture.md).
// It exists ONLY on the vnet: run these against `CORK_RPC_URL=<vnet>`; on real mainnet substitute
// a live poolId from api-phoenix.cork.tech/v1/pools/.
import type { ToolName } from "./registry.ts";

export const DEMO_POOL_ID = "0xceebea356e5159c9cb06612c39ef2e6e0fe9cd3bb047541e26e0c0767bd1c16a" as const;
export const DEMO_ACCOUNT = "0xc0ffee0000000000000000000000000000000001" as const;
const SUSDE = "0x9D39A5DE30e57443BfF2A8307A4256c8797A3497";
const VBUSDC = "0x53E82ABbb12638F09d9e624578ccB666217a765e";

// A real safeSwap Bundler3 multicall (1 sUSDe out of the demo pool, pre-funded), generated by
// cork_prepare_phoenix — decodes to one labeled cork leg.
const DEMO_MULTICALL =
  "0x374f435d000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000ccccccccccccbad6f772a511b337d9ccc957040700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4d5f2e59eceebea356e5159c9cb06612c39ef2e6e0fe9cd3bb047541e26e0c0767bd1c16a0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000c0ffee00000000000000000000000000000000010000000000000000000000000000000000000000000000001bc16d674ec8000000000000000000000000000000000000000000000000000000000000001e8480000000000000000000000000000000000000000000000000000000006a5e14e600000000000000000000000000000000000000000000000000000000";

export interface ToolExample {
  title: string;
  input: Record<string, unknown>;
}

/** 2–3 worked examples per tool; the FIRST is the one inlined into the wire description. */
export const TOOL_EXAMPLES: Record<ToolName, readonly ToolExample[]> = {
  cork_query: [
    { title: "Read a pool's full live market state (demo pool, vnet)", input: { resource: "market", filters: { poolId: DEMO_POOL_ID } } },
    { title: "Token balances an account holds in a pool", input: { resource: "account-state", filters: { poolId: DEMO_POOL_ID, account: DEMO_ACCOUNT } } },
    { title: "Deployed Cork contract addresses (no RPC needed)", input: { resource: "protocol-config" } },
  ],
  cork_compute: [
    { title: "How much cST + reference does 1 sUSDe out cost right now?", input: { params: { kind: "cst-swap-rate", poolId: DEMO_POOL_ID, collateralAssetsOut: "1000000000000000000" } } },
    { title: "Rollover premium floor (pure math, no RPC)", input: { params: { kind: "rollover-premium-floor", dstCstProduced: "1000000000000000000000", minPremiumPerShare: "20000000000000000" } } },
    { title: "Worst-case impairment floor over 1 day", input: { params: { kind: "impairment-floor", poolId: DEMO_POOL_ID, horizonSeconds: 86400 } } },
    { title: "Resolve a registry recipe's bands at a rate (Arbitrum; bands 1e18=1%, resolved 1e18=1.0)", input: { chainId: 42161, params: { kind: "resolve-recipe", mode: "liquidity", rate: "1000000000000000000" } } },
  ],
  cork_decode: [
    { title: "Decode a Bundler3 multicall to labeled Cork legs", input: { kind: "calldata", data: DEMO_MULTICALL } },
  ],
  cork_capabilities: [
    { title: "Find the right tool/variant for 'unwind'", input: { search: "unwind" } },
    { title: "Full doc for one tool", input: { topic: "compute" } },
    { title: "Re-derive deployed addresses via CREATE2", input: { topic: "verify" } },
  ],
  cork_prepare_phoenix: [
    { title: "Unsigned deposit bundle (10 sUSDe into the demo pool)", input: { chainId: 1, account: DEMO_ACCOUNT, clientRequestId: "demo-deposit-0001", fundingMode: "erc20-approve", action: { type: "deposit", poolId: DEMO_POOL_ID, collateralAssetsIn: "10000000000000000000", receiver: DEMO_ACCOUNT, minCptAndCstSharesOut: "1" } } },
    { title: "Unsigned swap bundle (1 sUSDe out, capped inputs)", input: { chainId: 1, account: DEMO_ACCOUNT, clientRequestId: "demo-swap-0001", action: { type: "swap", poolId: DEMO_POOL_ID, collateralAssetsOut: "1000000000000000000", receiver: DEMO_ACCOUNT, maxCstSharesIn: "2000000000000000000", maxReferenceAssetsIn: "2000000" } } },
  ],
  cork_prepare_orders: [
    { title: "Signable maker order: sell 1 sUSDe for 1 vbUSDC", input: { chainId: 1, account: DEMO_ACCOUNT, clientRequestId: "demo-order-0001", action: { type: "maker-order", poolId: DEMO_POOL_ID, side: "SELL", makerAsset: SUSDE, takerAsset: VBUSDC, makingAmount: "1000000000000000000", takingAmount: "1000000", expirySeconds: 3600 } } },
    { title: "Cancel calldata for a resting order", input: { chainId: 1, account: DEMO_ACCOUNT, clientRequestId: "demo-cancel-0001", action: { type: "cancel", orderHash: "0x1111111111111111111111111111111111111111111111111111111111111111", makerTraits: "0" } } },
    { title: "Signable rollover order (Arbitrum, ExactSettler, all-or-nothing)", input: { chainId: 42161, account: DEMO_ACCOUNT, clientRequestId: "demo-roll-0001", action: { type: "rollover-intent", settler: "0x983270AE48545665Cee4D7EF61C65fF3fdC8222D", rolloverContract: DEMO_ACCOUNT, srcPoolId: "0x1111111111111111111111111111111111111111111111111111111111111111", dstPoolId: "0x2222222222222222222222222222222222222222222222222222222222222222", srcCstToken: SUSDE, dstCstToken: VBUSDC, premiumToken: SUSDE, orderSize: "250000000000000000000", minPremiumPerShare: "12000000000000000", openDeadline: "1795000000", fillDeadline: "1795604800" } } },
  ],
  cork_prepare_market: [
    { title: "Unsigned oracle-deploy tx for a pair (registry.deploy — permissionless, idempotent; Arbitrum)", input: { chainId: 42161, clientRequestId: "demo-market-0001", action: { type: "deploy-wrapper", collateralAsset: "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2", referenceAsset: "0x7F6501d3B98eE91f9b9535E4b0ac710Fb0f9e0bc" } } },
  ],
  cork_track: [
    { title: "Digest-pin an artifact you were handed", input: { mode: "verify", subject: { kind: "artifact", artifact: { any: "json" } } } },
    { title: "Verify a pool against chain (MarketId re-hash)", input: { mode: "verify", subject: { kind: "marketRef", poolId: DEMO_POOL_ID } } },
    { title: "Reconcile a tx receipt", input: { mode: "reconcile", subject: { kind: "txHash", txHash: "0x2222222222222222222222222222222222222222222222222222222222222222" } } },
    { title: "Dry-run a prepared bundle before signing (wouldRevert + reason)", input: { mode: "simulate", subject: { kind: "artifact", artifact: { bundler3: "0x1FA4431bC113D308beE1d46B0e98Cb805FB48C13", multicall: "0x374f435d", account: DEMO_ACCOUNT } }, chainId: 42161 } },
  ],
  cork_submit: [
    { title: "Relay a signed rollover order to the venue (intent hash + digest recomputed before relay)", input: { chainId: 42161, clientRequestId: "demo-submit-0001", action: { type: "rollover-order", order: { user: DEMO_ACCOUNT, settler: "0x983270AE48545665Cee4D7EF61C65fF3fdC8222D", fillerHint: "0x0000000000000000000000000000000000000000", exclusiveFiller: "0x0000000000000000000000000000000000000000", srcCstToken: SUSDE, dstCstToken: VBUSDC, premiumToken: SUSDE, rolloverContract: DEMO_ACCOUNT, originChainId: "42161", destinationChainId: "42161", openDeadline: "1795000000", fillDeadline: "1795604800", orderSalt: "8811723641", orderSize: "250000000000000000000", minPremiumPerShare: "12000000000000000", allowPartialFills: false, allowUnderfill: false, premiumPaymentMode: 0, rolloverIntentHash: "0x93cec2a3f4ee806583f173da81e62a11d0a8b392ec9f1509e5f2228006f52d84", rolloverParams: { srcCstToken: SUSDE, dstCstToken: VBUSDC, minCaReceived: "0", minSharesOut: "0", srcPoolId: "0x1111111111111111111111111111111111111111111111111111111111111111", dstPoolId: "0x2222222222222222222222222222222222222222222222222222222222222222", settler: "0x983270AE48545665Cee4D7EF61C65fF3fdC8222D" } }, intent: { rolloverContract: DEMO_ACCOUNT, deadline: "1795604800", nonce: "1", preRolloverHooks: [], midRolloverHooks: [], postRolloverHooks: [], premiumHooks: [] }, signature: "0x8f3b00000000000000000000000000000000000000000000000000000000001c" } } },
    { title: "Open an RFQ (buyer): cover 50k, acceptable parameter envelope", input: { chainId: 42161, clientRequestId: "demo-rfq-0001", action: { type: "rfq-open", requester: DEMO_ACCOUNT, referenceAsset: SUSDE, collateralAsset: { one_of: [VBUSDC] }, modes: ["liquidity_impairment"], packageIds: ["balanced-v1"], expiryWindow: { notBefore: 1795000000, notAfter: 1795604800 }, notionalAssets: "50000000000", validUntil: 1794900000, signature: "0x00" } } },
  ],
};

// ─── Maturity map [R6]: specified (schema only) / implemented (code path, backend-gated) /
//     activated (works now with built-in defaults). Reasons are the same closed warning codes the
//     gated call would return — an agent can see the outcome without spending the call.
export type MaturityStatus = "activated" | "implemented" | "specified";
export interface VariantMaturity {
  status: MaturityStatus;
  reason?: string;
}
export interface ToolMaturity {
  status: MaturityStatus;
  reason?: string;
  variants?: Record<string, VariantMaturity>;
}

export const MATURITY: Record<ToolName, ToolMaturity> = {
  cork_query: {
    status: "activated",
    variants: {
      market: { status: "activated" },
      "account-state": { status: "activated", reason: "balances + funding allowances (corkAdapter + Permit2 spenders)" },
      "pool-whitelist": { status: "activated" },
      "protocol-config": { status: "activated" },
      markets: { status: "activated", reason: "centralized (venue /v1/pools) or full-decentralized (HyperSync MarketCreated scan, needs ENVIO_API_TOKEN)" },
      "whitelisted-addresses": { status: "specified", reason: "needs_indexer" },
      flows: { status: "activated", reason: "centralized (/v1/rollover, filters.kind orders|fills|contracts); kind fills|contracts also full-decentralized via HyperSync" },
      "limit-order-markets": { status: "activated", reason: "venue-backed (centralized mode)" },
      orderbook: { status: "activated", reason: "venue-backed (centralized mode)" },
      fills: { status: "activated", reason: "centralized (venue) or full-decentralized (HyperSync OrderFilled scan)" },
      "registry-assets": { status: "activated", reason: "MarketRegistry chain views — Arbitrum One (42161)" },
      "registry-oracle": { status: "activated", reason: "lookupWrapper + simulated deploy: deployed/deployable/why-not (42161)" },
      "registry-recipes": { status: "activated", reason: "constraint recipe bands, 1e18 = 1% (42161)" },
    },
  },
  cork_compute: {
    status: "activated",
    variants: {
      "cst-swap-rate": { status: "activated" },
      "unwind-rate": { status: "activated" },
      "impairment-floor": { status: "activated" },
      "rollover-premium-floor": { status: "activated" },
      "dutch-auction-price": { status: "specified", reason: "phase_gated (1inch Fusion, Phase 3)" },
      "rfq-quote": { status: "specified", reason: "phase_gated (pricing model TBD; the registry band math it needs is live as resolve-recipe)" },
      "resolve-recipe": { status: "activated", reason: "registry applyBands — bit-parity self-checked against chain on every call (42161)" },
    },
  },
  cork_decode: {
    status: "activated",
    variants: {
      calldata: { status: "activated" },
      order: { status: "specified", reason: "phase_gated" },
      event: { status: "specified", reason: "phase_gated" },
      receipt: { status: "specified", reason: "phase_gated" },
    },
  },
  cork_capabilities: { status: "activated" },
  cork_prepare_phoenix: {
    status: "activated",
    variants: {
      "13 adapter actions (mint…unwind-exercise-other)": { status: "activated" },
      "authority-onboard": { status: "specified", reason: "phase_gated" },
      "authority-revoke": { status: "specified", reason: "phase_gated" },
    },
  },
  cork_prepare_orders: {
    status: "activated",
    variants: {
      "maker-order": { status: "activated" },
      cancel: { status: "activated" },
      "taker-fill": { status: "specified", reason: "needs_service (orderbook)" },
      "rollover-intent": { status: "activated", reason: "offline typed-data build; domain-separator parity proven vs both live Arbitrum settlers" },
    },
  },
  cork_prepare_market: {
    status: "activated",
    reason: "Q-REG closed 2026-07-22: MarketRegistry verified on-chain (Arbitrum One); deploy-wrapper builds the permissionless idempotent registry.deploy(ca, ref) tx",
    variants: { "deploy-wrapper": { status: "activated" } },
  },
  cork_track: {
    status: "activated",
    variants: {
      "verify/artifact": { status: "activated" },
      "verify/marketRef": { status: "activated" },
      "reconcile/txHash": { status: "activated" },
      "simulate/artifact": { status: "activated", reason: "eth_call dry-run of frozen bytes (wouldRevert + reason + gas estimate); other subject kinds have nothing executable" },
      "reconcile/orderHash": { status: "activated", reason: "venue lifecycle + [K7] chain verification: settler orderStatus() over RPC (automatic) and event history via HyperRPC (needs ENVIO_API_TOKEN)" },
      "reconcile/submissionRef": { status: "activated", reason: "same as reconcile/orderHash; 32-byte digests only" },
    },
  },
  cork_submit: {
    status: "implemented",
    reason: "all four off-chain venue writes wired; activation pending the first live accepted POST",
    variants: {
      "rollover-order": { status: "implemented", reason: "K3 intent-hash + orderDigest recomputed before relay" },
      "lop-order": { status: "implemented", reason: "orderHash recomputed locally; extension/salt commitment pre-flight" },
      "rfq-open": { status: "implemented" },
      "rfq-answer": { status: "implemented" },
    },
  },
};

/** The wire-description example line for a tool (first example, compact JSON). */
export function descriptionExample(name: ToolName): string {
  const ex = TOOL_EXAMPLES[name]?.[0];
  return ex ? ` Example — ${ex.title}: ${JSON.stringify(ex.input)}` : "";
}
