[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false

[fmt]
sort_imports = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
